POST localhost:8082/games/
Content-Type: application/json

{
  "name": "Luca"
}

###

GET localhost:8082/games/

###

GET localhost:8082/games/1

###

POST localhost:8082/games/1
Content-Type: application/json

{
  "name": "Vasco"
}

###

PATCH localhost:8082/games/1/start

###

POST localhost:8082/games/1/players/1/move
Content-Type: application/json

{
  "posX": 2,
  "posY": 2
}

###

POST localhost:8082/games/1/players/1/bomb
Content-Type: application/json

{
  "posX":2,
  "posY":1
}

###

POST localhost:8082/games/1/players/1/move
Content-Type: application/json

{
  "posX":1,
  "posY":1
}

###

POST localhost:8082/games/1/players/1/move
Content-Type: application/json

{
  "posX":1,
  "posY":2
}

###
